### ISSUE TITLE
question

### ISSUE THREAD

**Issue by dsaldanag** [carloseustaquio/harvardCS50-tideman#1]
I am lost on this part:

void record_preferences(int ranks[])
{
    /*
        Creates/update the pairs. ranks[i] represents the winner
        and ranks[j] represents the loser, as j always start one
        place after i (j = i + 1).
        So, for example, if the voter rank was [2 0 1], the voter
        prefers 2 over 1 and 0, and prefers 1 over 0! It means that,
        the function should increment the pairs [2, 0] [2, 1] and
        [0, 1]
    */

    for (int i = 0; i < candidate_count; i++)
    {
        for (int j = i + 1; j < candidate_count; j++)
        {
            preferences[ranks[i]][ranks[j]]++;
        }
    }
    return;
}

The ranks array is the input of the function but then the code is not referring to the array.

Then, from my understanding, the first loop is preferences[0][1]++ but how is this checking that 2 is preferred over 0 and then add 1. For me, this loop reads as:
preferences[0][1]++
preferences[0][2]++
....
preferences[1][2]++
preferences[1][3]++
etc.

**Comment by carloseustaquio** [comment]
I'm referencing the ranks[] array in this part: `preferences[ranks[i]][ranks[j]]++;`
See that inside the preferences array I'm not passing the values of `i` or `j`, I'm passing the `i`th and `j`th positions of the ranks array!
You can take a look on what's been saved in the preferences[] array by uncommenting the debug helper 1
